# Generated by Django 4.2.13 on 2025-04-13 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.TextField()),
                ("category", models.TextField()),
                ("address", models.TextField()),
                ("visitor_reviews", models.IntegerField()),
                ("blog_reviews", models.IntegerField()),
                ("description_or_menu", models.TextField()),
            ],
            options={
                "db_table": "store_reviews",
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField(unique=True)),
                ("title", models.TextField()),
                ("upload_date", models.DateField()),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "videos",
            },
        ),
        migrations.CreateModel(
            name="VideoStoreLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.storereview",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.video"
                    ),
                ),
            ],
            options={
                "db_table": "video_store_links",
            },
        ),
    ]
